Repository sivanmah/sunshine-amigos, pull requests merged in 2021-04, with the labels that each got.

#5 Initial coding
  assets/css/animations.css
  assets/css/content.min.css
  assets/css/page.css
  assets/css/page.min.css
  assets/img/exampleImage.png
  assets/img/leaves.svg
  assets/img/tree_without_leaves.svg
  assets/scss/_rules.scss
  assets/scss/content.scss
  assets/scss/page.scss
  index.html
Labels: core

#12 Scrolling
  assets/js/animations.js
  assets/js/exampleScript.js
  assets/js/stepScrolling.js
  assets/js/toggleScrolling.js
  index.html
Labels: core, feature

#15 Scrolling
  assets/js/stepScrolling.js
  assets/js/toggleScrolling.js
Labels: core, enhancement

#20 Animations: Shorten & Simplify Code
  assets/css/animations.min.css
  assets/scss/animations.scss
Labels: cleanup

#25 Documentation cleanup & minor CSS "DRYing"
  README.md
  assets/css/index.min.css
  assets/scss/_content.scss
Labels: cleanup, documentation

#23 SCSS cleanup
  assets/animations/_frame1.scss
  assets/animations/_frame10.scss
  assets/animations/_frame2.scss
  assets/animations/_frame3.scss
  assets/animations/_frame4.scss
  assets/animations/_frame5.scss
  assets/animations/_frame6.scss
  assets/animations/_frame7.scss
  assets/animations/_frame8.scss
  assets/animations/_frame9.scss
  assets/animations/_keyframes.scss
  assets/css/index.min.css
  assets/img/apples.svg
  assets/img/heart.svg
  assets/img/man.svg
  assets/js/animations.js
  assets/js/stepScrolling.js
  assets/scss/_animations.scss
  assets/scss/_content.scss
  assets/scss/_rules.scss
  assets/scss/index.scss
  assets/styles/content/_clouds.scss
  assets/styles/content/_human_silhouette.scss
  assets/styles/content/_tree.scss
  assets/styles/content/_verse.scss
  assets/styles/index.min.css
  assets/styles/index.min.css.map
  assets/styles/index.scss
  assets/styles/rules/_colors.scss
  assets/styles/rules/_fonts.scss
  assets/styles/rules/_rules.scss
  index.html
Labels: cleanup
